[tool.black]
line-length = 119
target-version = ['py39']
include = '\.py$'
exclude = '''
(
    migrations
    | /venv
    | /.tox
)
'''

[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
skip_glob = "*/migrations/*.py, /venv"
